### PR TITLE
Feature auto tiling

### PR DESCRIPTION
**Pull request by jantwegener**
Added the feature of auto-tiling.
A new tab "Auto Tiling" is added to the Tiles dialog. One can drop images containing the complete tiles images (corners, full, single tiles, etc.) into the Auto Tiling tab. After selecting an auto-tiling-tile, one can draw the tiles into the sandbox. After releasing the mouse button, the tiles are chosen according to their surrounding.

The two example templates demonstrate the position of each tile within the auto tiling template image.
template-autotile-extended
template-autotile-extended-2
Unfortunately, with this design of the template, 3 slots are unused. Furthermore, it is not possible to cover all possible combinations.

The following image demonstrates an example:
image

Furthermore, added and adjusted the feature to highlights the dragged and target. Somehow forgot to push it :/

### CODE REVIEW

**Comment by fgnm** [comment]
Hi, sorry for late answer. This PR is really cool! Many thanks for it. I've noticed few issue at moment:
- Tile size is not correctly set when selecting an auto tile image, right click on an auto tile doesn't allow to set grid size. It's easy to reach this result if there're other normal tiles (spaces between tiles). A `set grid size` option with a right click would be great.
immagine
- Tiles selection now looks a bit buggy, I guess something with drag n drop tiles reorder
immagine
- Tabs have weird width, but I think this may be caused by the custom tab widget (I'll check this)
- Once tiles are divided it's impossible to delete them from the project, then from a more theoretical point of view these new PNGs created should fall back into new atlas packing system. One idea could be to create a new atlas pack inside `ProjectInfoVO#imagesPacks`, like I did for [atlas import](https://github.com/rednblackgames/HyperLap2D/blob/431b871bc300102b20b7d8360567ef4a4134b8b4/src/main/java/games/rednblack/editor/utils/asset/impl/AtlasAsset.java#L52). Later, if the user want to pack them differently will be able to do it.
- Regarding all placement possibilities we can adjust the `autoFill` algorithm in future :)

Let me know!

**Comment by jantwegener** [comment]
Hi @fgnm,

No worries, we all are busy :) Thanks for the feedback, I have already corrected some of the issues.

- "Added" the set grid size option (more like uncommenting it); same way as it already exists for tiles
- The buggy tiles selection was when the drag source and target were equal. This bug is now corrected. Furthermore, added the selection of the drag & drop source after dropping.
- I appreciate that you have a look into better sizing the tabs. It already took me quite some time to make it the way it looks right now. And in between it was even more creepy :D
- I will have a look into the atlas importer and see what I can do.
- Yes, I can imagine different kind of templates as well. At first I was experimenting with a smaller tile-set (with only 16 tiles).
- Another idea for the future is the possibility to set alias-tile-sets. The autofill algorithm could then randomly choose between the different tile-sets. This would bring more life into an auto-tiled scenery. In addition, the user could set the distribution of the random selection (e.g., 80% ts1, 10% ts2, 10% ts3).

**Comment by Minecraftian14** [comment]
* I opened an old project
* Downloaded and imported the blue tiles sample you gave
* A dragged that from Resources drop to Auto Tiling's drop.
* And suddenly I have a crash...

java.lang.ClassCastException: class games.rednblack.editor.plugin.tiled.data.TileVO cannot be cast to class games.rednblack.editor.plugin.tiled.data.AutoTileVO (games.rednblack.editor.plugin.tiled.data.TileVO and games.rednblack.editor.plugin.tiled.data.AutoTileVO are in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @1cbf6e72)
	at games.rednblack.editor.plugin.tiled.TiledPanelMediator.handleNotification(TiledPanelMediator.java:149)
	at org.puremvc.java.patterns.observer.Observer.notifyObserver(Observer.java:72)
	at org.puremvc.java.core.View.lambda$notifyObservers$0(View.java:131)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
	at org.puremvc.java.core.View.notifyObservers(View.java:131)
	at org.puremvc.java.patterns.facade.Facade.notifyObservers(Facade.java:428)
	at org.puremvc.java.patterns.facade.Facade.sendNotification(Facade.java:386)
	at org.puremvc.java.patterns.facade.Facade.sendNotification(Facade.java:399)
	at games.rednblack.editor.plugin.tiled.view.tabs.AbstractGridTilesTab.addTile(AbstractGridTilesTab.java:88)
	at games.rednblack.editor.plugin.tiled.TiledPanel.addAutoTile(TiledPanel.java:179)
	at games.rednblack.editor.plugin.tiled.TiledPanelMediator.handleNotification(TiledPanelMediator.java:132)
	at org.puremvc.java.patterns.observer.Observer.notifyObserver(Observer.java:72)
	at org.puremvc.java.core.View.lambda$notifyObservers$0(View.java:131)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
	at org.puremvc.java.core.View.notifyObservers(View.java:131)
	at org.puremvc.java.patterns.facade.Facade.notifyObservers(Facade.java:428)
	at org.puremvc.java.patterns.facade.Facade.sendNotification(Facade.java:386)
	at org.puremvc.java.patterns.facade.Facade.sendNotification(Facade.java:399)
	at games.rednblack.editor.plugin.tiled.TiledPanelMediator$1.drop(TiledPanelMediator.java:327)
	at com.badlogic.gdx.scenes.scene2d.utils.DragAndDrop$1.dragStop(DragAndDrop.java:153)
	at com.badlogic.gdx.scenes.scene2d.utils.DragListener.touchUp(DragListener.java:67)
	at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:71)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:355)
	at com.badlogic.gdx.InputMultiplexer.touchUp(InputMultiplexer.java:124)
	at com.badlogic.gdx.InputEventQueue.drain(InputEventQueue.java:70)
	at com.badlogic.gdx.backends.lwjgl3.DefaultLwjgl3Input.update(DefaultLwjgl3Input.java:189)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:394)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:143)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:116)
	at games.rednblack.editor.Main.main(Main.java:67)

**Comment by jantwegener** [comment]
Hi @Minecraftian14 
Thank you for the bug report. It should be fixed now. Please try again with the latest commit.
Thanks

**Comment by Minecraftian14** [comment]
Awesome Thing!!!
But it seems there's still a lot of work to be done...
EpicWorld

**Comment by Minecraftian14** [comment]
Oh, i just realised that it currently doesnt work for some specific tiles!
Sorry for that

**Comment by jantwegener** [comment]
@Minecraftian14 Thanks for providing a complete tileset :) Please let me know if you find a missplaced tile with the new implementation.

**Comment by Minecraftian14** [comment]
This arrangement shows all the tile configurations. There might be a lot more efficient ones, but currently this is what i got.

As you can, the inner corner tile, or whatever it's called 😅, is incorrectly placed and instead has a all flat tile in it's place. 

image

**Comment by jantwegener** [comment]
Thanks for the bug-report :)

Corrected:
* wrongly set tiles (the one you found and one when two tiles only touch diagonally, e.g., like a Y)
* delete tool when clicking on a tile (includes hot-swap)

Furthermore, when drawing instead of squashing the tile-set, the tile 18 (inner dirt, outer all grass) is used to draw on the sandbox. Hope you meant that tile :smiley:

**Comment by jantwegener** [comment]
Added the possibilities of alternatives for the auto-tiles.
image

**Comment by Minecraftian14** [comment]
I went on and got this link:
http://www.cr31.co.uk/stagecast/wang/intro.html

Suddenly i feel like i have been doing everything wrong with my tile set creator 😅

I hope it helps you too 👍

**Comment by fgnm** [comment]
Okay fixed some stuff and merged into master, thanks all :)

**Pull request merged**
